// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.9
// source: lootbox.proto

package lootbox_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LootBox_RollLootBoxRewards_FullMethodName = "/accelbyte.platform.entitlement.lootbox.v1.LootBox/RollLootBoxRewards"
)

// LootBoxClient is the client API for LootBox service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LootBoxClient interface {
	// *
	// RollLootBoxRewards
	RollLootBoxRewards(ctx context.Context, in *RollLootBoxRewardsRequest, opts ...grpc.CallOption) (*RollLootBoxRewardsResponse, error)
}

type lootBoxClient struct {
	cc grpc.ClientConnInterface
}

func NewLootBoxClient(cc grpc.ClientConnInterface) LootBoxClient {
	return &lootBoxClient{cc}
}

func (c *lootBoxClient) RollLootBoxRewards(ctx context.Context, in *RollLootBoxRewardsRequest, opts ...grpc.CallOption) (*RollLootBoxRewardsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RollLootBoxRewardsResponse)
	err := c.cc.Invoke(ctx, LootBox_RollLootBoxRewards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LootBoxServer is the server API for LootBox service.
// All implementations should embed UnimplementedLootBoxServer
// for forward compatibility.
type LootBoxServer interface {
	// *
	// RollLootBoxRewards
	RollLootBoxRewards(context.Context, *RollLootBoxRewardsRequest) (*RollLootBoxRewardsResponse, error)
}

// UnimplementedLootBoxServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLootBoxServer struct{}

func (UnimplementedLootBoxServer) RollLootBoxRewards(context.Context, *RollLootBoxRewardsRequest) (*RollLootBoxRewardsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RollLootBoxRewards not implemented")
}
func (UnimplementedLootBoxServer) testEmbeddedByValue() {}

// UnsafeLootBoxServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LootBoxServer will
// result in compilation errors.
type UnsafeLootBoxServer interface {
	mustEmbedUnimplementedLootBoxServer()
}

func RegisterLootBoxServer(s grpc.ServiceRegistrar, srv LootBoxServer) {
	// If the following call panics, it indicates UnimplementedLootBoxServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LootBox_ServiceDesc, srv)
}

func _LootBox_RollLootBoxRewards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollLootBoxRewardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LootBoxServer).RollLootBoxRewards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LootBox_RollLootBoxRewards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LootBoxServer).RollLootBoxRewards(ctx, req.(*RollLootBoxRewardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LootBox_ServiceDesc is the grpc.ServiceDesc for LootBox service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LootBox_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accelbyte.platform.entitlement.lootbox.v1.LootBox",
	HandlerType: (*LootBoxServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RollLootBoxRewards",
			Handler:    _LootBox_RollLootBoxRewards_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lootbox.proto",
}
