// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.9
// source: lootbox.proto

package lootbox_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RollLootBoxRewardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"` // the lootbox quantity to be opened
	ItemInfo      *LootBoxItemInfo       `protobuf:"bytes,4,opt,name=itemInfo,proto3" json:"itemInfo,omitempty"`  // lootbox item info
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollLootBoxRewardsRequest) Reset() {
	*x = RollLootBoxRewardsRequest{}
	mi := &file_lootbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollLootBoxRewardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollLootBoxRewardsRequest) ProtoMessage() {}

func (x *RollLootBoxRewardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lootbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollLootBoxRewardsRequest.ProtoReflect.Descriptor instead.
func (*RollLootBoxRewardsRequest) Descriptor() ([]byte, []int) {
	return file_lootbox_proto_rawDescGZIP(), []int{0}
}

func (x *RollLootBoxRewardsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RollLootBoxRewardsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RollLootBoxRewardsRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *RollLootBoxRewardsRequest) GetItemInfo() *LootBoxItemInfo {
	if x != nil {
		return x.ItemInfo
	}
	return nil
}

type RollLootBoxRewardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rewards       []*RewardObject        `protobuf:"bytes,1,rep,name=rewards,proto3" json:"rewards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollLootBoxRewardsResponse) Reset() {
	*x = RollLootBoxRewardsResponse{}
	mi := &file_lootbox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollLootBoxRewardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollLootBoxRewardsResponse) ProtoMessage() {}

func (x *RollLootBoxRewardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lootbox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollLootBoxRewardsResponse.ProtoReflect.Descriptor instead.
func (*RollLootBoxRewardsResponse) Descriptor() ([]byte, []int) {
	return file_lootbox_proto_rawDescGZIP(), []int{1}
}

func (x *RollLootBoxRewardsResponse) GetRewards() []*RewardObject {
	if x != nil {
		return x.Rewards
	}
	return nil
}

type RewardObject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=itemId,proto3" json:"itemId,omitempty"`
	ItemSku       string                 `protobuf:"bytes,2,opt,name=itemSku,proto3" json:"itemSku,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"` // The number of this item awarded
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RewardObject) Reset() {
	*x = RewardObject{}
	mi := &file_lootbox_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewardObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewardObject) ProtoMessage() {}

func (x *RewardObject) ProtoReflect() protoreflect.Message {
	mi := &file_lootbox_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewardObject.ProtoReflect.Descriptor instead.
func (*RewardObject) Descriptor() ([]byte, []int) {
	return file_lootbox_proto_rawDescGZIP(), []int{2}
}

func (x *RewardObject) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *RewardObject) GetItemSku() string {
	if x != nil {
		return x.ItemSku
	}
	return ""
}

func (x *RewardObject) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type LootBoxItemInfo struct {
	state          protoimpl.MessageState                 `protogen:"open.v1"`
	ItemId         string                                 `protobuf:"bytes,1,opt,name=itemId,proto3" json:"itemId,omitempty"`                 // lootbox item id
	ItemSku        string                                 `protobuf:"bytes,2,opt,name=itemSku,proto3" json:"itemSku,omitempty"`               // lootbox item sku
	RewardCount    int32                                  `protobuf:"varint,3,opt,name=rewardCount,proto3" json:"rewardCount,omitempty"`      // How many rewards can be obtained by opening a lootbox
	LootBoxRewards []*LootBoxItemInfo_LootBoxRewardObject `protobuf:"bytes,4,rep,name=lootBoxRewards,proto3" json:"lootBoxRewards,omitempty"` // lootbox reward config
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LootBoxItemInfo) Reset() {
	*x = LootBoxItemInfo{}
	mi := &file_lootbox_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LootBoxItemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LootBoxItemInfo) ProtoMessage() {}

func (x *LootBoxItemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_lootbox_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LootBoxItemInfo.ProtoReflect.Descriptor instead.
func (*LootBoxItemInfo) Descriptor() ([]byte, []int) {
	return file_lootbox_proto_rawDescGZIP(), []int{3}
}

func (x *LootBoxItemInfo) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *LootBoxItemInfo) GetItemSku() string {
	if x != nil {
		return x.ItemSku
	}
	return ""
}

func (x *LootBoxItemInfo) GetRewardCount() int32 {
	if x != nil {
		return x.RewardCount
	}
	return 0
}

func (x *LootBoxItemInfo) GetLootBoxRewards() []*LootBoxItemInfo_LootBoxRewardObject {
	if x != nil {
		return x.LootBoxRewards
	}
	return nil
}

type BoxItemObject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=itemId,proto3" json:"itemId,omitempty"`
	ItemSku       string                 `protobuf:"bytes,2,opt,name=itemSku,proto3" json:"itemSku,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoxItemObject) Reset() {
	*x = BoxItemObject{}
	mi := &file_lootbox_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoxItemObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoxItemObject) ProtoMessage() {}

func (x *BoxItemObject) ProtoReflect() protoreflect.Message {
	mi := &file_lootbox_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoxItemObject.ProtoReflect.Descriptor instead.
func (*BoxItemObject) Descriptor() ([]byte, []int) {
	return file_lootbox_proto_rawDescGZIP(), []int{4}
}

func (x *BoxItemObject) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *BoxItemObject) GetItemSku() string {
	if x != nil {
		return x.ItemSku
	}
	return ""
}

func (x *BoxItemObject) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type LootBoxItemInfo_LootBoxRewardObject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`      // reward name
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`      // reward type: REWARD/PROBABILITY_GROUP
	Items         []*BoxItemObject       `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`    // reward items
	Weight        int32                  `protobuf:"varint,4,opt,name=weight,proto3" json:"weight,omitempty"` // reward weight
	Odds          float64                `protobuf:"fixed64,5,opt,name=odds,proto3" json:"odds,omitempty"`    // reward odds: [0.00, 100.00], Odds are calculated automatically(weight / total weight), keeping 2 decimal places
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LootBoxItemInfo_LootBoxRewardObject) Reset() {
	*x = LootBoxItemInfo_LootBoxRewardObject{}
	mi := &file_lootbox_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LootBoxItemInfo_LootBoxRewardObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LootBoxItemInfo_LootBoxRewardObject) ProtoMessage() {}

func (x *LootBoxItemInfo_LootBoxRewardObject) ProtoReflect() protoreflect.Message {
	mi := &file_lootbox_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LootBoxItemInfo_LootBoxRewardObject.ProtoReflect.Descriptor instead.
func (*LootBoxItemInfo_LootBoxRewardObject) Descriptor() ([]byte, []int) {
	return file_lootbox_proto_rawDescGZIP(), []int{3, 0}
}

func (x *LootBoxItemInfo_LootBoxRewardObject) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LootBoxItemInfo_LootBoxRewardObject) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LootBoxItemInfo_LootBoxRewardObject) GetItems() []*BoxItemObject {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *LootBoxItemInfo_LootBoxRewardObject) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *LootBoxItemInfo_LootBoxRewardObject) GetOdds() float64 {
	if x != nil {
		return x.Odds
	}
	return 0
}

var File_lootbox_proto protoreflect.FileDescriptor

const file_lootbox_proto_rawDesc = "" +
	"\n" +
	"\rlootbox.proto\x12)accelbyte.platform.entitlement.lootbox.v1\"\xc5\x01\n" +
	"\x19RollLootBoxRewardsRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12V\n" +
	"\bitemInfo\x18\x04 \x01(\v2:.accelbyte.platform.entitlement.lootbox.v1.LootBoxItemInfoR\bitemInfo\"o\n" +
	"\x1aRollLootBoxRewardsResponse\x12Q\n" +
	"\arewards\x18\x01 \x03(\v27.accelbyte.platform.entitlement.lootbox.v1.RewardObjectR\arewards\"V\n" +
	"\fRewardObject\x12\x16\n" +
	"\x06itemId\x18\x01 \x01(\tR\x06itemId\x12\x18\n" +
	"\aitemSku\x18\x02 \x01(\tR\aitemSku\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"\x99\x03\n" +
	"\x0fLootBoxItemInfo\x12\x16\n" +
	"\x06itemId\x18\x01 \x01(\tR\x06itemId\x12\x18\n" +
	"\aitemSku\x18\x02 \x01(\tR\aitemSku\x12 \n" +
	"\vrewardCount\x18\x03 \x01(\x05R\vrewardCount\x12v\n" +
	"\x0elootBoxRewards\x18\x04 \x03(\v2N.accelbyte.platform.entitlement.lootbox.v1.LootBoxItemInfo.LootBoxRewardObjectR\x0elootBoxRewards\x1a\xb9\x01\n" +
	"\x13LootBoxRewardObject\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12N\n" +
	"\x05items\x18\x03 \x03(\v28.accelbyte.platform.entitlement.lootbox.v1.BoxItemObjectR\x05items\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\x05R\x06weight\x12\x12\n" +
	"\x04odds\x18\x05 \x01(\x01R\x04odds\"W\n" +
	"\rBoxItemObject\x12\x16\n" +
	"\x06itemId\x18\x01 \x01(\tR\x06itemId\x12\x18\n" +
	"\aitemSku\x18\x02 \x01(\tR\aitemSku\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count2\xad\x01\n" +
	"\aLootBox\x12\xa1\x01\n" +
	"\x12RollLootBoxRewards\x12D.accelbyte.platform.entitlement.lootbox.v1.RollLootBoxRewardsRequest\x1aE.accelbyte.platform.entitlement.lootbox.v1.RollLootBoxRewardsResponseB\x9a\x01\n" +
	"-net.accelbyte.platform.entitlement.lootbox.v1B\flootBoxProtoP\x01Z-accelbyte.net/platform/entitlement/lootbox_v1\xaa\x02)Accelbyte.Platform.Entitlement.Lootbox.V1b\x06proto3"

var (
	file_lootbox_proto_rawDescOnce sync.Once
	file_lootbox_proto_rawDescData []byte
)

func file_lootbox_proto_rawDescGZIP() []byte {
	file_lootbox_proto_rawDescOnce.Do(func() {
		file_lootbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lootbox_proto_rawDesc), len(file_lootbox_proto_rawDesc)))
	})
	return file_lootbox_proto_rawDescData
}

var file_lootbox_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_lootbox_proto_goTypes = []any{
	(*RollLootBoxRewardsRequest)(nil),           // 0: accelbyte.platform.entitlement.lootbox.v1.RollLootBoxRewardsRequest
	(*RollLootBoxRewardsResponse)(nil),          // 1: accelbyte.platform.entitlement.lootbox.v1.RollLootBoxRewardsResponse
	(*RewardObject)(nil),                        // 2: accelbyte.platform.entitlement.lootbox.v1.RewardObject
	(*LootBoxItemInfo)(nil),                     // 3: accelbyte.platform.entitlement.lootbox.v1.LootBoxItemInfo
	(*BoxItemObject)(nil),                       // 4: accelbyte.platform.entitlement.lootbox.v1.BoxItemObject
	(*LootBoxItemInfo_LootBoxRewardObject)(nil), // 5: accelbyte.platform.entitlement.lootbox.v1.LootBoxItemInfo.LootBoxRewardObject
}
var file_lootbox_proto_depIdxs = []int32{
	3, // 0: accelbyte.platform.entitlement.lootbox.v1.RollLootBoxRewardsRequest.itemInfo:type_name -> accelbyte.platform.entitlement.lootbox.v1.LootBoxItemInfo
	2, // 1: accelbyte.platform.entitlement.lootbox.v1.RollLootBoxRewardsResponse.rewards:type_name -> accelbyte.platform.entitlement.lootbox.v1.RewardObject
	5, // 2: accelbyte.platform.entitlement.lootbox.v1.LootBoxItemInfo.lootBoxRewards:type_name -> accelbyte.platform.entitlement.lootbox.v1.LootBoxItemInfo.LootBoxRewardObject
	4, // 3: accelbyte.platform.entitlement.lootbox.v1.LootBoxItemInfo.LootBoxRewardObject.items:type_name -> accelbyte.platform.entitlement.lootbox.v1.BoxItemObject
	0, // 4: accelbyte.platform.entitlement.lootbox.v1.LootBox.RollLootBoxRewards:input_type -> accelbyte.platform.entitlement.lootbox.v1.RollLootBoxRewardsRequest
	1, // 5: accelbyte.platform.entitlement.lootbox.v1.LootBox.RollLootBoxRewards:output_type -> accelbyte.platform.entitlement.lootbox.v1.RollLootBoxRewardsResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_lootbox_proto_init() }
func file_lootbox_proto_init() {
	if File_lootbox_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lootbox_proto_rawDesc), len(file_lootbox_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lootbox_proto_goTypes,
		DependencyIndexes: file_lootbox_proto_depIdxs,
		MessageInfos:      file_lootbox_proto_msgTypes,
	}.Build()
	File_lootbox_proto = out.File
	file_lootbox_proto_goTypes = nil
	file_lootbox_proto_depIdxs = nil
}
